### ISSUE TITLE
Stopped Working

### ISSUE THREAD

**Issue by tsunrise0** [alike03/Userscripts#4]
Hi, today (14/04/2020), the script stopped working for me. Tampermonkey claims script was executed properly. I'm guessing some code change at Youtube's end in the recent days caused this.

**Comment by alike03** [comment]
Hey, I changed the load order. Is it after an updated solved? Otherwise, you can try to set the Run at: to document-end so the script runs after YouTube has fully loaded. It's under Tampermonkey Icon > Dashboard > Edit Youtube Docking > Settings > Run at: document-end. And also YouTube is down right now. Maybe it's linked.
